POST  http://127.0.0.1:3000/login
Content-Type: application/json
 
{
    "email": "cl@cl.cl",
    "password": "internal"
}

###
POST  http://127.0.0.1:3000/usuarios
Content-Type: application/json 

{
    "email": "cl@cl.cl",
    "password": "internal",
    "rol": "admin",
    "lenguage": "logo"
}